### ISSUE TITLE
Execute other code blocks before current block

### ISSUE THREAD

**Issue by dalbandea** [dbridges/vim-markdown-runner#2]
Hi, thank you for the nice plugin.

It would be great if one could write some code callable from code blocks below. For instance, for python one could write all necessary libraries in a code block,
```python
import numpy as np
```
and be able to use the library in the next code block,
```python
a = np.array([1,2])
```
Do you think it would be easy to implement?

**Comment by dbridges** [comment]
This is a bit beyond the scope of the project, but you could potentially look into firing up a Jupyter session and communicating with that. This would all be very python specific and I'd like to keep the project generally useful.
