### ISSUE TITLE
Keep session and environment variables

### ISSUE THREAD

**Issue by LeNouveau** [dbridges/vim-markdown-runner#4]
Hi, 

I often start my documentation with the following block 

``` bash
export username="John DOE"
```

and then use those variables. 

``` bash
echo "Hello $username"
```

but I lose my `username` variable. 

Is there a solution to keep the same session ? 
(while the document is opened)

Regards, 
LeNouveau

**Comment by dbridges** [comment]
Yes, for now every time a code block is run it runs in a new environment. This is mostly just for simplicity, as hooking up to an external session is more advanced functionality than this plugin is designed for.

**Comment by LeNouveau** [comment]
Thank you for the confirmation. 
Regards.
